"""add_api_users_table

Revision ID: 5cf0b4c5e8c7
Revises: f8a9b0c1d2e3
Create Date: 2026-05-13 00:26:19.614512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf0b4c5e8c7'
down_revision: Union[str, None] = 'f8a9b0c1d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comorbidities_patient_id', table_name='comorbidities')
    op.drop_constraint('icu_admissions_mimic_icustay_id_key', 'icu_admissions', type_='unique')
    op.drop_index('ix_icu_admissions_patient_id', table_name='icu_admissions')
    op.create_index(op.f('ix_icu_admissions_mimic_icustay_id'), 'icu_admissions', ['mimic_icustay_id'], unique=True)
    op.drop_index('ix_lab_results_patient_id', table_name='lab_results')
    op.drop_index('lab_results_collected_at_idx', table_name='lab_results')
    op.drop_index('vital_readings_recorded_at_idx', table_name='vital_readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('vital_readings_recorded_at_idx', 'vital_readings', [sa.text('recorded_at DESC')], unique=False)
    op.create_index('lab_results_collected_at_idx', 'lab_results', [sa.text('collected_at DESC')], unique=False)
    op.create_index('ix_lab_results_patient_id', 'lab_results', ['patient_id'], unique=False)
    op.drop_index(op.f('ix_icu_admissions_mimic_icustay_id'), table_name='icu_admissions')
    op.create_index('ix_icu_admissions_patient_id', 'icu_admissions', ['patient_id'], unique=False)
    op.create_unique_constraint('icu_admissions_mimic_icustay_id_key', 'icu_admissions', ['mimic_icustay_id'])
    op.create_index('ix_comorbidities_patient_id', 'comorbidities', ['patient_id'], unique=False)
    # ### end Alembic commands ###
