"""composite_pk_vital_readings

Revision ID: 7ba73f65e710
Revises: ec92c99e777b
Create Date: 2026-03-23 01:53:37.665609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba73f65e710'
down_revision: Union[str, None] = 'ec92c99e777b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vital_readings_recorded_at', table_name='vital_readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vital_readings_recorded_at', 'vital_readings', ['recorded_at'], unique=False)
    # ### end Alembic commands ###
