"""add_api_users_table_v2

Revision ID: d0c751dd5084
Revises: 5cf0b4c5e8c7
Create Date: 2026-05-13 00:27:44.288216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c751dd5084'
down_revision: Union[str, None] = '5cf0b4c5e8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_users_api_key'), 'api_users', ['api_key'], unique=True)
    op.create_index(op.f('ix_api_users_username'), 'api_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_users_username'), table_name='api_users')
    op.drop_index(op.f('ix_api_users_api_key'), table_name='api_users')
    op.drop_table('api_users')
    # ### end Alembic commands ###
